//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport_Inventar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public int IdRole { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string PatronymicName { get; set; }
        public string UserEmail { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
        public string UserPhoneNum { get; set; }
        public Nullable<int> UserSeriaPass { get; set; }
        public Nullable<int> UserNumPass { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateLastEnter { get; set; }
        public Nullable<int> IdTypeEnter { get; set; }
        public int IdGender { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Role Role { get; set; }
        public virtual TypeEnter TypeEnter { get; set; }
    }
}
